#!/usr/bin/env bash

# Create a backup of the /etc/hosts file, so you can restore it in case of an error.
sudo cp /etc/hosts /etc/hosts.bak

# This line deletes any existing entry containing 'localhost' in the /etc/hosts file.
sudo sed -i '/localhost/d' /etc/hosts

# Then, it adds a new entry associating the IP 127.0.0.2 with 'localhost'.
# 'tee -a' appends this entry to the end of the file, without overwriting it.
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

# This line deletes any existing entry containing 'facebook.com' in the /etc/hosts file.
sudo sed -i '/facebook.com/d' /etc/hosts

# It adds a new entry that makes 'facebook.com' resolve to the IP 8.8.8.8.
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null

# Prints a message in the terminal indicating that the /etc/hosts file has been updated.
echo "Updated /etc/hosts:"

# Displays the updated contents of the /etc/hosts file, so you can verify the changes.
cat /etc/hosts